"""
gen_dispatch.py

Generates pack_dispatch.h — a C++ dispatcher that provides the full
gemm_blis.h API:

  void pack_CB_v(char orderM, char transM, int mc, int nc,
                 float* M, int ldM, float* Mc, int RR);

  void pack_RB_v(char orderM, char transM, int mc, int nc,
                 float* M, int ldM, float* Mc, int RR);

The dispatcher routes to the generated branch kernels based on the same
condition used in gemm_blis.c (lines 174, 210):

  if ( ((transM=='N')&&(orderM=='C')) || ((transM=='T')&&(orderM=='R')) )
    → pack_CB_v_if_{suffix}_RR{NR}  / pack_RB_v_if_{suffix}_RR{MR}
  else
    → pack_CB_v_else_{suffix}_RR{NR} / pack_RB_v_else_{suffix}_RR{MR}

A runtime assert ensures the caller's RR matches the compiled block size,
catching configuration mismatches early.

Usage:
  python gen_dispatch.py --NR 8 --MR 4 --suffix fp32 --output pack_dispatch.h
"""

import argparse

HEADER_TEMPLATE = """\
/**
 * pack_dispatch.h  [GENERATED — do not edit manually]
 *
 * Generated by: gen_dispatch.py --NR {NR} --MR {MR} --suffix {suffix}
 *
 * Provides the full gemm_blis.h-compatible API:
 *   pack_CB_v(orderM, transM, mc, nc, M, ldM, Mc, RR)
 *   pack_RB_v(orderM, transM, mc, nc, M, ldM, Mc, RR)
 *
 * Branch condition (exact copy from gemm_blis.c lines 174, 210):
 *   if ( ((transM=='N')&&(orderM=='C')) || ((transM=='T')&&(orderM=='R')) )
 *
 * Compiled block sizes: NR={NR} (CB/B-matrix), MR={MR} (RB/A-matrix)
 * Dtype: {suffix}  Element bytes: {elem_bytes}
 */
#pragma once
#include <cassert>
#include <cstddef>

// ── Generated kernel declarations ─────────────────────────────────────────────
extern "C" {{
    // pack_CB_v branches (NR={NR}, Col-Block packing of B)
    void pack_CB_v_if_{suffix}_RR{NR}  ({ctype}* M, {ctype}* Mc, size_t mc, size_t nc, size_t ldM);
    void pack_CB_v_else_{suffix}_RR{NR}({ctype}* M, {ctype}* Mc, size_t mc, size_t nc, size_t ldM);

    // pack_RB_v branches (MR={MR}, Row-Block packing of A)
    void pack_RB_v_if_{suffix}_RR{MR}  ({ctype}* M, {ctype}* Mc, size_t mc, size_t nc, size_t ldM);
    void pack_RB_v_else_{suffix}_RR{MR}({ctype}* M, {ctype}* Mc, size_t mc, size_t nc, size_t ldM);
}}

// ── pack_CB_v ─────────────────────────────────────────────────────────────────
// Matches gemm_blis.h signature exactly.
// RR must equal NR={NR}; asserted at runtime.
inline void pack_CB_v(char orderM, char transM,
                      int mc, int nc, {ctype}* M, int ldM, {ctype}* Mc, int RR) {{
    assert(RR == {NR} && "pack_CB_v: RR must equal compiled NR={NR}");
    if ( ((transM=='N') && (orderM=='C')) ||
         ((transM=='T') && (orderM=='R')) )
        pack_CB_v_if_{suffix}_RR{NR}  (M, Mc, (size_t)mc, (size_t)nc, (size_t)ldM);
    else
        pack_CB_v_else_{suffix}_RR{NR}(M, Mc, (size_t)mc, (size_t)nc, (size_t)ldM);
}}

// ── pack_RB_v ─────────────────────────────────────────────────────────────────
// Matches gemm_blis.h signature exactly.
// RR must equal MR={MR}; asserted at runtime.
inline void pack_RB_v(char orderM, char transM,
                      int mc, int nc, {ctype}* M, int ldM, {ctype}* Mc, int RR) {{
    assert(RR == {MR} && "pack_RB_v: RR must equal compiled MR={MR}");
    if ( ((transM=='N') && (orderM=='C')) ||
         ((transM=='T') && (orderM=='R')) )
        pack_RB_v_if_{suffix}_RR{MR}  (M, Mc, (size_t)mc, (size_t)nc, (size_t)ldM);
    else
        pack_RB_v_else_{suffix}_RR{MR}(M, Mc, (size_t)mc, (size_t)nc, (size_t)ldM);
}}
"""

SUFFIX_TO_CTYPE = {
    "fp32": "float",
    "fp16": "_Float16",
    "i8":   "int8_t",
    "i32":  "int32_t",
}

SUFFIX_TO_BYTES = {
    "fp32": 4,
    "fp16": 2,
    "i8":   1,
    "i32":  4,
}


def generate(NR: int, MR: int, suffix: str, output: str):
    ctype     = SUFFIX_TO_CTYPE.get(suffix, "float")
    elem_bytes = SUFFIX_TO_BYTES.get(suffix, 4)
    content   = HEADER_TEMPLATE.format(
        NR=NR, MR=MR, suffix=suffix, ctype=ctype, elem_bytes=elem_bytes
    )
    with open(output, "w") as f:
        f.write(content)
    print(f"✅ Generated: {output}  (NR={NR}, MR={MR}, dtype={suffix})")


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--NR",     type=int, default=8,      help="CB block width  (B-matrix tile cols)")
    p.add_argument("--MR",     type=int, default=4,      help="RB block height (A-matrix tile rows)")
    p.add_argument("--suffix", type=str, default="fp32", help="dtype suffix: fp32|fp16|i8|i32")
    p.add_argument("--output", type=str, default="tests/packing/pack_dispatch.h")
    args = p.parse_args()
    generate(args.NR, args.MR, args.suffix, args.output)
