/**
 * pack_dispatch.h  [GENERATED — do not edit manually]
 *
 * Generated by: gen_dispatch.py --NR 8 --MR 4 --suffix fp32
 *
 * Provides the full gemm_blis.h-compatible API:
 *   pack_CB_v(orderM, transM, mc, nc, M, ldM, Mc, RR)
 *   pack_RB_v(orderM, transM, mc, nc, M, ldM, Mc, RR)
 *
 * Branch condition (exact copy from gemm_blis.c lines 174, 210):
 *   if ( ((transM=='N')&&(orderM=='C')) || ((transM=='T')&&(orderM=='R')) )
 *
 * Compiled block sizes: NR=8 (CB/B-matrix), MR=4 (RB/A-matrix)
 * Dtype: fp32  Element bytes: 4
 */
#pragma once
#include <cassert>
#include <cstddef>

// ── Generated kernel declarations ─────────────────────────────────────────────
extern "C" {
    // pack_CB_v branches (NR=8, Col-Block packing of B)
    void pack_CB_v_if_fp32_RR8  (float* M, float* Mc, size_t mc, size_t nc, size_t ldM);
    void pack_CB_v_else_fp32_RR8(float* M, float* Mc, size_t mc, size_t nc, size_t ldM);

    // pack_RB_v branches (MR=4, Row-Block packing of A)
    void pack_RB_v_if_fp32_RR4  (float* M, float* Mc, size_t mc, size_t nc, size_t ldM);
    void pack_RB_v_else_fp32_RR4(float* M, float* Mc, size_t mc, size_t nc, size_t ldM);
}

// ── pack_CB_v ─────────────────────────────────────────────────────────────────
// Matches gemm_blis.h signature exactly.
// RR must equal NR=8; asserted at runtime.
inline void pack_CB_v(char orderM, char transM,
                      int mc, int nc, float* M, int ldM, float* Mc, int RR) {
    assert(RR == 8 && "pack_CB_v: RR must equal compiled NR=8");
    if ( ((transM=='N') && (orderM=='C')) ||
         ((transM=='T') && (orderM=='R')) )
        pack_CB_v_if_fp32_RR8  (M, Mc, (size_t)mc, (size_t)nc, (size_t)ldM);
    else
        pack_CB_v_else_fp32_RR8(M, Mc, (size_t)mc, (size_t)nc, (size_t)ldM);
}

// ── pack_RB_v ─────────────────────────────────────────────────────────────────
// Matches gemm_blis.h signature exactly.
// RR must equal MR=4; asserted at runtime.
inline void pack_RB_v(char orderM, char transM,
                      int mc, int nc, float* M, int ldM, float* Mc, int RR) {
    assert(RR == 4 && "pack_RB_v: RR must equal compiled MR=4");
    if ( ((transM=='N') && (orderM=='C')) ||
         ((transM=='T') && (orderM=='R')) )
        pack_RB_v_if_fp32_RR4  (M, Mc, (size_t)mc, (size_t)nc, (size_t)ldM);
    else
        pack_RB_v_else_fp32_RR4(M, Mc, (size_t)mc, (size_t)nc, (size_t)ldM);
}
